services:
  nodejs:
    image: node:latest
    container_name: nodejs-app
    working_dir: /usr/src/app
    volumes:
      - ../nodejs:/usr/src/app  # Подключение внешней папки с проектом
    ports:
      - "${APP_PORT}:3000"  # Порт берется из .env
    command: ["npm", "run", "start"]  # Команда для запуска приложения
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    env_file:
      - ../configs.env  # Переменные из .env файла для этого сервиса

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro  # Подключение пользовательского конфигурационного файла
    depends_on:
      - nodejs
    # env_file:
    #   - ../configs.env  # Переменные из .env файла для этого сервиса

  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "${DB_PORT}:5432"  # Порт берется из .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # env_file:
    #   - ../configs.env  # Переменные из .env файла для этого сервиса
